exclude: ^(docs)/
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.0.1
  hooks:
    - id: check-merge-conflict
    - id: check-toml
    - id: check-yaml
    - id: trailing-whitespace
    - id: end-of-file-fixer
    # - id: requirements-txt-fixer
- repo: https://github.com/PyCQA/isort
  rev: 5.10.1
  hooks:
    - id: isort
      name: isort
      args: ["--profile", "black"]
- repo: https://github.com/asottile/pyupgrade
  rev: v2.29.1
  hooks:
    - id: pyupgrade
      args: [--py38-plus]
- repo: https://github.com/psf/black
  rev: 22.6.0
  hooks:
  - id: black
    name: black
    description: "Black: The uncompromising Python code formatter"
    entry: black
    language: python
    minimum_pre_commit_version: 2.9.2
    require_serial: true
    types_or: [python, pyi]
- repo: https://github.com/PyCQA/pylint
  rev: v2.12.2
  hooks:
    - id: pylint
      args: [--rcfile=.pylintrc]
      files: ^.*\.py
